import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Test MercadoPago",
  description: "Generated by ibra",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={cn("bg-background font-sans antialiased dark")}>
        {children}
      </body>
    </html>
  );
}
